name: discord-cloud-system

services:
  discord-server:
    container_name: discord-cloud-system
    build:
      context: .
    restart: always
    ports:
      - 2500:2500
    env_file:
      - .env
    volumes:
      - ./Data:/app/Data
